version: '3.1'

services:
  app:
    container_name: sir-soir
    image: sir-soir
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - dbpostgresql

  dbpostgresql:
    container_name: sir-soir-db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sir-db-data/:/var/lib/postgresql/data